[package]
name = "day18"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name = "day18p1"
path = "src/day18p1.rs"

[[bin]]
name = "day18p2"
path = "src/day18p2.rs"


[dependencies]
